# Generated by Django 4.2.3 on 2023-07-17 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('DR', 'DIRECTOR'), ('AD', 'ADMINISTRATOR'), ('TR', 'TEACHER'), ('ST', 'STUDENT')], default='ST', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('linkedin_token', models.TextField(blank=True, default='')),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('active_time', models.DateField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('active_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('period', models.IntegerField()),
                ('begin_date', models.DateField()),
                ('complete_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('salary', models.IntegerField()),
                ('image', models.ImageField(upload_to='teacher_images/')),
                ('active_time', models.DateField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('profession', models.ManyToManyField(related_name='profession_t', to='app.profession')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('phone', models.IntegerField()),
                ('extra_phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=150, null=True, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('profession', models.ManyToManyField(related_name='profession_s', to='app.profession')),
                ('teachers', models.ManyToManyField(to='app.teacher')),
                ('technologies', models.ManyToManyField(related_name='technologies', to='app.technology')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.groups')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='students',
            field=models.ManyToManyField(related_name='students', to='app.student'),
        ),
        migrations.AddField(
            model_name='groups',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
        migrations.AddField(
            model_name='groups',
            name='technologies',
            field=models.ManyToManyField(related_name='group_technology', to='app.technology'),
        ),
        migrations.AddField(
            model_name='groups',
            name='week_days',
            field=models.ManyToManyField(related_name='days', to='app.weekdays'),
        ),
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.CharField(max_length=255)),
                ('keldi', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomat', to='app.student')),
            ],
        ),
    ]
