# Generated by Django 4.1.9 on 2023-07-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='extra_phone_number',
        ),
    ]
