# Generated by Django 4.1.9 on 2023-07-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_student_extra_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='src',
            field=models.ImageField(null=True, upload_to='student_image/'),
        ),
    ]
