# Generated by Django 4.1.9 on 2023-07-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='sana',
            field=models.DateField(max_length=255),
        ),
    ]
