# Generated by Django 4.1.9 on 2023-07-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_davomat_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='keldi',
            field=models.CharField(max_length=5),
        ),
    ]
