# Generated by Django 4.1.9 on 2023-07-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_student_when_start_groups_when_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='image',
            new_name='src',
        ),
    ]
