# Generated by Django 4.1.9 on 2023-07-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_image_teacher_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='technologies',
            field=models.ManyToManyField(related_name='technologies_t', to='app.technology'),
        ),
    ]
