# Generated by Django 4.1.9 on 2023-07-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_teacher_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teachers',
        ),
    ]
