# Generated by Django 4.1.9 on 2023-07-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_student_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
