# Generated by Django 4.1.9 on 2023-07-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_payment_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
