# Generated by Django 4.1.9 on 2023-07-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_student_src_remove_teacher_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='period',
        ),
        migrations.AlterField(
            model_name='groups',
            name='begin_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='groups',
            name='complete_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='groups',
            name='when_start',
            field=models.CharField(max_length=50),
        ),
    ]
