# Generated by Django 4.1.9 on 2023-07-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_groups_period_alter_groups_begin_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='active_time',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='updated_time',
        ),
    ]
