# Generated by Django 4.1.9 on 2023-07-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_teacher_active_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='active_time',
        ),
        migrations.RemoveField(
            model_name='director',
            name='updated_time',
        ),
    ]
