# Generated by Django 4.1.9 on 2023-07-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_director_active_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='active_time',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='updated_time',
        ),
    ]
