# Generated by Django 4.1.9 on 2023-07-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_admin_active_time_remove_admin_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='sana',
            field=models.CharField(max_length=255),
        ),
    ]
