# Generated by Django 4.1.9 on 2023-07-25 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_davomat_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profession'),
        ),
    ]
