# Generated by Django 4.1.9 on 2023-07-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_technology_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='profession',
        ),
        migrations.AddField(
            model_name='technology',
            name='profession',
            field=models.ManyToManyField(related_name='technologies', to='app.profession'),
        ),
    ]
