# Generated by Django 4.1.9 on 2023-07-25 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_technology_profession_technology_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='profession',
        ),
        migrations.AddField(
            model_name='technology',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='app.profession'),
        ),
    ]
