# Generated by Django 4.1.9 on 2023-07-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_technology_profession_technology_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
