# Generated by Django 4.1.9 on 2023-07-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_payment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='davomat',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.groups'),
        ),
    ]
