# Generated by Django 4.1.9 on 2023-07-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_davomat_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checks',
            field=models.FileField(null=True, upload_to='checks'),
        ),
    ]
