# Generated by Django 4.1.9 on 2023-07-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_payment_checks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='checks',
        ),
    ]
