# Generated by Django 4.1.9 on 2023-07-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_payment_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='technologies',
        ),
    ]
