# Generated by Django 4.1.9 on 2023-08-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_student_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='keldi',
            field=models.CharField(max_length=55),
        ),
    ]
